name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
  
      - name: Run tests
        run: poetry run pytest
        
  build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GICR_SAMPLEAPP }}    

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:      
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sample-api:latest